version: "3.3"

services:
  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:v1.152.1
    restart: always
    expose:
      - 8008
    environment:
      - SYNAPSE_REGISTRATION_SHARED_SECRET=${REG_SECRET}
      - SYNAPSE_MACAROON_SECRET_KEY=${MACAROON_SECRET}
      - SYNAPSE_FORM_SECRET=${FORM_SECRET}
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
      - SYNAPSE_RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC}
      - SYNAPSE_RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE}
    volumes:
      - ./matrix/data:/data
    
  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - synapse