services:
  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:v1.152.1
    restart: always
    expose:
      - 8008
    volumes:
      - ./matrix/data:/data

  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "8080:80"
    restart: always
    environment:
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
    volumes:
      - ./nginx/templates/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - synapse

  tuna_matrix:
    container_name: tuna_matrix
    image: yuccastream/tuna:latest
    restart: always
    network_mode: "host"
    environment:
      - TUNA_TOKEN=${TUNA_TOKEN}
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
    command: http 8080 --domain=${SYNAPSE_SERVER_NAME} --https-redirect
    depends_on:
      - nginx

  tuna_ssh:
    container_name: tuna_ssh
    image: yuccastream/tuna:latest
    restart: always
    network_mode: "host"
    environment:
      - TUNA_TOKEN=${TUNA_TOKEN}
    command: tcp 22 --port=frolov-ssh